### ISSUE TITLE
Zero thresholdPrecision breaks passing tests

### ISSUE THREAD

**Issue by razetdinov** [degiro/jest-coverage-processor#1]
Our goal is to:
1) autoupdate coverage threshold;
2) minimize merge conflicts in package.json.

So we set threshold to 0 in order to update only whole-number percents.

Problem:
1. Jest outputs 5.69% coverage.
2. JCP writes 6% to package.json.
3. Jest breaks (coverage threshold not met).

**Comment by webschik** [comment]
Fixed in v1.1.0
